### ISSUE TITLE
Stop Winston from crapping web server log lines to the console

### ISSUE THREAD

**Issue by ackinc** [pesto-students/project-delta#49]
It's interfering with console.logs I'm adding for debugging purposes. We should redirect them to some log file instead.

**Comment by vipulrawat** [comment]
I've formatted the winston's console logs now. Will be easier to distinguish your debugging console.logs after 'std-profile-BE' PR #51.

**Comment by ackinc** [comment]
This is what I see when I run tests. 
![1](https://user-images.githubusercontent.com/4007598/47248657-736bea80-d429-11e8-8b27-528963d78952.png)

I find those log lines distracting, and not very useful for debugging, plus, heroku automatically does request-logging for us in prod. You can access them by running heroku log --app <APP_NAME> from the CLI. Look in the picture below for the lines labeled 'router'.
![2](https://user-images.githubusercontent.com/4007598/47248751-381deb80-d42a-11e8-9840-629dfc1274d4.png)

My suggestion is to remove these logs completely from our code.

@bharaninb what do you think about this?

**Comment by bharaninb** [comment]
We need to remove console logs for tests. It's difficult to view test results.

**Comment by ackinc** [comment]
@vipulrawat One of today's PRs removed the express.use(morgan...) line to remove these unwanted logs. If you really want the logs, you can do this:
1. Add an npm script to API's package.json like "start:dev:logs": "nodemon ... --logging"
2. Use process.argv, or the npm package minimist to conditionally activate logging (express.use(morgan...)) if the extra "--logging" arg was provided

But please make sure logging is *not* the default way to start:dev, since the majority of devs on the team don't want it. Let me know if you want a more detailed explanation
